# text_stats_toolkit - auto-generated by code_toolkit_demo workflow

class TextStatsToolkit:
    """Text statistics tools: word count, keyword extraction, and summarisation."""
    __toolkit__ = True

    def word_count(self, text: str) -> dict:
        """Count words, sentences, and characters in text.
        Returns a dict with keys: words, sentences, chars, avg_word_len."""
        import re
        words = text.split()
        sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
        return {
            "words":        len(words),
            "sentences":    len(sentences),
            "chars":        len(text),
            "avg_word_len": round(sum(len(w) for w in words) / max(len(words), 1), 1),
        }

    def extract_keywords(self, text: str, top_n: int = 5) -> list:
        """Extract the most frequent meaningful words from text.
        top_n: number of keywords to return (default 5)."""
        import re
        STOP = {
            "the","a","an","is","are","was","were","be","been","have","has",
            "had","do","does","did","will","would","could","should","may",
            "might","must","can","it","its","this","that","and","but","or",
            "nor","for","in","of","on","to","at","by","from","with","not",
            "no","as","if","so","then","than","also","into","over","after",
        }
        words = re.findall(r"[a-z']+", text.lower())
        words = [w for w in words if w not in STOP and len(w) > 3]
        counts = {}
        for w in words:
            counts[w] = counts.get(w, 0) + 1
        return sorted(counts, key=lambda k: counts[k], reverse=True)[:top_n]

    def summarize(self, text: str) -> str:
        """Return the first sentence as a quick extractive summary."""
        import re
        sentences = re.split(r'(?<=[.!?])\s+', text.strip())
        return sentences[0] if sentences else text[:200]
